# Generated by Django 4.2.5 on 2023-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_watchlist_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="in_watchlist",
            field=models.CharField(default="no", max_length=64),
        ),
    ]
